Zone parkingspots frontend
dominicnzl/DriveDok pull request #108
Opened 2021-02-03 15:37 UTC by GeenEva

Some error checks are allready done. Have to look at writing the tests later. (Maybe only in Postman?)

2021-02-03 19:09 UTC, dominicnzl requested changes

2021-02-03 19:09 UTC, dominicnzl commented on src/test/java/nl/conspect/drivedok/controllers/ZoneControllerTest.java
> +        Zone zone = new Zone("Zone 1",  100);
Je zou hier regel 108 t/m 113 kunnen weglaten en de test zal nog steeds slagen. 

~~Eigenlijk wil je denk ik aantonen dat als je de update methode aanroept, de originele waarden worden vervangen met de nieuw geupdate waarden.~~ (doe je natuurlijk al in je service test 👍)

2021-02-04 07:51 UTC, mdeinum commented on pom.xml
> +			<version>1.11.1</version>
Heb je jQuery überhaupt nodig? Met de huidige staat van dom selectors etc. heb je deze heel vaak al niet nodig. Of gebruiken jullie bootstrap element waar jQuery voor nodig is?

2021-02-04 07:51 UTC, mdeinum commented on src/main/resources/templates/zone.html
> +    <script th:src="@{/webjars/jquery/1.11.1/jquery.min.js}"></script>
Waarom de een via een CDN en de ander lokaal? Of alles via een CDN of alles lokaal.

2021-02-04 07:59 UTC, arnoutvw requested changes

2021-02-04 07:59 UTC, arnoutvw commented on src/main/resources/templates/zone.html
>  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
Waarom hier nog een script kan die niet bovenin staan met de rest?

2021-02-04 07:59 UTC, arnoutvw commented on src/main/resources/templates/zonecreateform.html
> +    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
is het niet mogelijk een include te maken met deze standaard link/scripts?

2021-02-04 07:59 UTC, arnoutvw commented on src/main/resources/templates/zonehome.html
> +        <h2>Welcome Administrator Bert,</h2>
Is Bert altijd Admin?

2021-02-04 09:30 UTC, GeenEva commented on src/main/resources/templates/zonecreateform.html
> +    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
Afhankelijk van hoe retorisch je vraag is denk ik dat het antwoord ja is, maar ik ben bang dat ik niet helemaal begrijp wat je bedoelt...  Wil je het toelichten?

2021-02-04 09:32 UTC, GeenEva commented on src/main/resources/templates/zonehome.html
> +        <h2>Welcome Administrator Bert,</h2>
ja, hij krijgt het druk
maar komt dus als we de koppeling met de users hebben gemaakt ja

2021-02-04 09:36 UTC, arnoutvw commented on src/main/resources/templates/zonecreateform.html
> +    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
Nou ja ik ken thymleaf niet helemaal dus weet niet of het mogelijk is. Maar het idee ervan is dat je maar op 1 plek eventueel alle versies hoeft aan te passen ipv in alle webpagina's

2021-02-05 08:23 UTC, dominicnzl commented on pom.xml
> +			<version>1.11.1</version>
We gebruiken [Bootstrap 5](https://getbootstrap.com/docs/5.0/getting-started/javascript/), die vereist geen jQuery.

2021-02-05 12:29 UTC, GeenEva commented on pom.xml
> +			<version>1.11.1</version>
aangepast

2021-02-05 12:29 UTC, GeenEva commented on src/main/java/nl/conspect/drivedok/exceptions/ParkingSpotUpdateException.java
> +        super(format("Your Parkingspot was unable to update properly"));
aangepast

2021-02-05 12:30 UTC, GeenEva commented on src/test/java/nl/conspect/drivedok/controllers/ZoneControllerTest.java
> +        mockMvc.perform(get("/zones/1"))
alle tests werkende. moet alleen tests schrijven voor update zone. hier een issue voor aangemaakt.

2021-02-05 12:30 UTC, GeenEva commented on src/test/java/nl/conspect/drivedok/controllers/ZoneControllerTest.java
> +        mockMvc.perform(get("/zones/create"))
alle tests werkende. moet alleen tests schrijven voor update zone. hier een issue voor aangemaakt.

2021-02-05 12:30 UTC, GeenEva commented on src/main/resources/templates/zone.html
> +            <input type="hidden" th:field="*{totalParkingSpots}" th:id="myTotalParkingSpots"}>
aangepast

2021-02-05 13:08 UTC, GeenEva commented on src/main/resources/templates/zone.html
> +        /*<![CDATA[*/
ga ik naar kijken, kom ik later op terug
CDATA afsluiting aangepast

2021-02-05 13:08 UTC, GeenEva commented on src/main/resources/templates/zone.html
> +            let myTotal = document.getElementById("myTotalParkingSpots").value;
aangepast

2021-02-05 13:12 UTC, GeenEva commented on src/main/resources/templates/zone.html
> +            $(document)
issue voor aangemaakt

2021-02-05 13:15 UTC, GeenEva commented on src/main/resources/templates/zone.html
> +                temp = normal-(current - prev);
temp = 10 -8-2   = 0
temp = 10 -(8-2) = 4
lijkt mij een vrij evident verschil... dus ik laat de haakjes even staan als je het goed vindt ;)

2021-02-05 13:17 UTC, GeenEva commented on src/test/java/nl/conspect/drivedok/controllers/ZoneControllerTest.java
> +        Zone zone = new Zone("Zone 1",  100);
Alle tests voor deze update moeten nog in overleg worden aangemaakt... lekker TDD not, hopelijk komen we er gauw uit

2021-02-05 13:23 UTC, GeenEva commented on pom.xml
> +			<version>1.11.1</version>
heb te weinig ervaring om dit even gauw te beantwoorden, dus issue voor aangemaakt om dit uit te zoeken

2021-02-05 13:24 UTC, GeenEva commented on src/main/resources/templates/zone.html
> +    <script th:src="@{/webjars/jquery/1.11.1/jquery.min.js}"></script>
aangepast

2021-02-05 13:25 UTC, GeenEva commented on src/main/resources/templates/zone.html
>  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
volgens de website van bootstrap moet die onderaan geloof ik

2021-02-05 13:28 UTC, GeenEva commented on src/main/resources/templates/zonecreateform.html
> +    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
ga ik uitzoeken

2021-02-05 16:52 UTC, dominicnzl commented on src/main/resources/templates/zone.html
> +                temp = normal-(current - prev);
Ah duurde even voordat ik het door had 🤡

Ik sta gecorrigeerd!

2021-02-05 17:11 UTC, dominicnzl commented on src/main/resources/templates/zone.html
> +                    normal =   parseInt(document.getElementById("NORMAL").value);
Waar gebruik je deze `normal` voor? 

Ik vind het hier niet gebruikersvriendelijk om de values van "Disabled" en "Electric" hard op 0  te zetten.

2021-02-08 13:24 UTC, dominicnzl commented on src/main/resources/templates/zone.html
>  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
Is idd zoals dat op de [Bootstrap site](https://getbootstrap.com/docs/5.0/getting-started/introduction/#js) beschreven staat: 

> Place one of following <script>s near the end of your pages, right before the closing </body> tag, to enable them.

2021-02-08 20:23 UTC, Daniel-Jacob approved these changes

2021-02-08 20:23 UTC, Daniel-Jacob commented on src/main/java/nl/conspect/drivedok/controllers/ZoneController.java
> +@RequestMapping("zones")
Waarom deze change? /home is toch ook niet /homes bijvoorbeeld?

2021-02-08 20:23 UTC, Daniel-Jacob commented on src/main/java/nl/conspect/drivedok/exceptions/ParkingSpotUpdateException.java
> +public class ParkingSpotUpdateException extends RuntimeException {
Moet dit geen RuntimeException(String message) zijn?

2021-02-08 20:23 UTC, Daniel-Jacob commented on src/main/java/nl/conspect/drivedok/controllers/ZoneController.java
> +        return "zonehome";
Waarom heet de logical view name niet homepage bijvoorbeeld?

2021-02-08 20:23 UTC, Daniel-Jacob commented on src/main/java/nl/conspect/drivedok/controllers/ZoneController.java
> +        return "zonecreateform";
Heb je ook andere forms met prefix zone en suffix form? Anders kan het gewoon zoneform heten lijkt me

2021-02-09 08:49 UTC, dominicnzl approved these changes

2021-02-09 08:52 UTC, GeenEva commented on src/main/java/nl/conspect/drivedok/controllers/ZoneController.java
> +        return "zonehome";
Ik denk dat we later een andere homepage krijgen, een inlogpagina

2021-02-09 08:56 UTC, GeenEva commented on src/main/java/nl/conspect/drivedok/controllers/ZoneController.java
> +        return "zonehome";
issue aangemaakt hiervoor

2021-02-09 08:57 UTC, GeenEva commented on src/main/java/nl/conspect/drivedok/controllers/ZoneController.java
> +        return "zonecreateform";
ja, ook voor users

2021-02-09 09:01 UTC, merged