Parkingspot availabilities
dominicnzl/DriveDok pull request #128
Opened 2021-02-10 15:00 UTC by GeenEva

Op deze manier wil ik de Zones de beschikbaarheid (availability) van parkingspots laten hebben, zodat bij een reservering (waarbij de user eerst een zone kiest) deze waarde er is en gecheckt kan worden of een reservering gemaakt kan worden. De reservering moet vervolgens deze waarde aanpassen.
Graag jullie feedback over deze aanpak.

2021-02-10 15:33 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/model/Zone.java
> +        for (ParkingSpot parkingSpot : parkingSpots) {
Je zou ook dit kunnen doen (hoeft niet):

```
    public void setParkingSpots(Set<ParkingSpot> parkingSpots) {
        Set<ParkingSpot> parkingSpots1 = new TreeSet<>(new ParkingTypeComparator());
        parkingSpots1.addAll(parkingSpots);
        this.parkingSpots = parkingSpots1;
    }
```

2021-02-10 15:41 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/services/ZoneServiceImpl.java
> +        parkingSpots.forEach(parkingSpot -> parkingSpot.setAvailability(parkingSpot.getQuantity()));
Zoals ik het hier lees zul je bij elke update aanroep voor de `parkingspots` van de `zone` die je meegeeft, altijd de `availability` gelijk zetten aan de `quantity`. Is dat ook echt zo bedoeld?

2021-02-10 15:50 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/model/Zone.java
> +        for (ParkingSpot parkingSpot : parkingSpots) {
Nee dat werkt niet. Hiermee vervang je een managed collection en dan gaat je JPA provider van het padje.

2021-02-10 15:54 UTC, mdeinum requested changes

2021-02-10 15:54 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/model/ParkingSpot.java
> +
Probleem hiermee is als 2 mensen tegelijkertijd een update doen, je een grote kans hebt dat deze data corrupt wordt. Nu kun je hier met transactie levels omheen werken maar het blijft een risico. Is het niet beter om op basis van een reservering het aantal beschikbare plaatsen voor een bepaalde datum/tijd te herleiden?

2021-02-10 15:54 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/model/Zone.java
> +        return id.equals(zone.id) && name.equals(zone.name);
Dus als de naam wijzigt is opeens ook de identiteit van het object gewijzigd (dat vindt JPA over het algemeen niet zo leuk). Zelfde geldt voor de `hashCode`.

2021-02-10 15:54 UTC, mdeinum commented on src/main/resources/templates/zone.html
>                      document.getElementById("DISABLED").value = 0;
Je hebt een enum (soort van dynamisch) maar hardcoded waardes in je HTML. Dat kan vast slimmer...

2021-02-10 15:57 UTC, dominicnzl commented on src/test/java/nl/conspect/drivedok/services/ZoneServiceTest.java
> +        System.out.println(afterUpdateZone);
Liever een logger (die van slf4j bijvoorbeeld) gebruiken ipv System.out.println.

Zet `Logger logger = LoggerFactory.getLogger(ZoneServiceTest.class);` bovenaan in de class waar je je andere fields definieert. Vervang de println statement met `logger.info(afterUpdateZone.toString());`

2021-02-11 07:40 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/model/Zone.java
> +        for (ParkingSpot parkingSpot : parkingSpots) {
wist ik niet, thanks!

2021-02-12 09:48 UTC, Daniel-Jacob requested changes

2021-02-12 09:48 UTC, Daniel-Jacob commented on src/main/java/nl/conspect/drivedok/model/ParkingType.java
> +    NORMAL, DISABLED, ELECTRIC, MOTOR;
Dus als ik de enums omwissel dan breekt het parking spots algoritme? Waarom is dat zo?

2021-02-12 09:48 UTC, Daniel-Jacob commented on src/test/java/nl/conspect/drivedok/services/ZoneServiceTest.java
> +    void updateZone() {
Ik mis tests for de unhappy flow.  Wellicht kan je ook een test schrijven voor het volgende stuk. Oftwewel vul de test met data die niet overeenkomt en schrijf een assertion dat de ParkingSpotUpdateException gegooid wordt. Wat gebeurt er trouwens verder met deze exceptie als die gegooid wordt? 

if(zone.getTotalParkingSpots() != sumOfParkingSpots){
            throw new ParkingSpotUpdateException();	            throw new ParkingSpotUpdateException();
        }	        }

2021-02-12 09:48 UTC, Daniel-Jacob commented on src/main/java/nl/conspect/drivedok/model/Zone.java
> +            parkingSpots1.add(parkingSpot);
hmm kan je hier niet gewoon een stream maken, sort methode aanroepen op de parking spots en een comparator meegeven en vervolgens collectors.ToSet doen en dat dan retourneren?

2021-02-24 11:43 UTC, mdeinum approved these changes

2021-03-03 09:23 UTC, mdeinum approved these changes

2021-03-04 09:53 UTC, mdeinum approved these changes

2021-03-08 06:48 UTC, mdeinum approved these changes

2021-03-08 10:19 UTC, mdeinum approved these changes

2021-03-08 10:42 UTC, dominicnzl commented on src/test/java/nl/conspect/drivedok/controllers/ZoneControllerTest.java
> +        List<Zone> expected = new ArrayList<Zone>(Arrays.asList(zone1, zone2, zone3));
Arrays.asList(args...) geeft al een ArrayList terug per default - het is hier niet nodig om het in een new ArrayList te wrappen. Kan dus worden vervangen met:

`List<Zone> expected = Arrays.asList(zone1, zone2, zone3);`

of nog korter:

`var expected = List.of(zone1, zone2, zone3);`

2021-03-08 11:12 UTC, dominicnzl approved these changes

2021-03-08 11:13 UTC, merged