Reservation entity and service
dominicnzl/DriveDok pull request #137
Opened 2021-02-15 17:24 UTC by dominicnzl

2021-02-16 10:20 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/model/Reservation.java
> +    @OneToOne
Hier wil ik dat de Reservation van de User, Vehicle en ParkingSpot weet maar niet per se andersom. Ik heb daarom bij die entities geen @JoinColumn gebruikt, maar weet niet zeker of ik het hier goed doe. Kunnen jullie hier wat over zeggen?

2021-02-16 10:43 UTC, mdeinum requested changes

2021-02-16 10:43 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/model/Reservation.java
> +    @OneToOne
Het is toch geen `@OneToOne` eerder alleen de `@ManyToOne` en dan met een `@JoinColumn` aangezien het dan een uni-directionele relatie is ipv. een bi-directionele relatie.

2021-02-16 10:43 UTC, mdeinum commented on src/test/java/nl/conspect/drivedok/services/ReservationServiceImplTest.java
> +        assertEquals(Optional.of(reservation), service.findById(entity.getId()));
Je voert hier 2x een `findById` uit waarom? Daarbij zou ik de [AssertJ](http://joel-costigliola.github.io/assertj/) library aanraden voor assertions (die wordt ook standaard meegeleverd met `spring-boot-starter-test` en dan wordt de code zoiets 

```java
assertThat(service.findById(entity.getId()).hasValue(entity);
```
Als het resultaat dan leeg is, krijg je al een foutmelding (scheelt je een assert :) ). 

Tot slot zou je eigenlijk na de `service.create(reservation);` een `testEntityManager.clear()` moeten doen. Momenteel heb je geen garantie dat hij daadwerkelijk uit de database komt maar eerder uit de first level cache.

2021-02-16 10:43 UTC, mdeinum commented on src/test/java/nl/conspect/drivedok/services/ReservationServiceImplTest.java
> +class ReservationServiceImplTest {
De vraag is wat wil je eigenlijk testen... Momenteel ben je min of meer Spring Data JPA aan het testen en niet zo zeer je eigen functionaliteit. Mogelijk dat je dit beter kunt testen met een volledige integratie test `@SpringBootTest` vanaf de voorkant en dan je service valideren met een simpelere unit test middels mocks.

2021-02-16 11:36 UTC, dominicnzl commented on src/test/java/nl/conspect/drivedok/services/ReservationServiceImplTest.java
> +class ReservationServiceImplTest {
Ah ja ik dacht nog eigenlijk waarom mock ik de repository niet... want nu gebruik ik zowel de service als repo.

Ik denk dat de `@SpringBootTest` integratie test pas goed kan wanneer ik de controller heb aangemaakt? Of bedoel je toch iets anders?

2021-02-16 11:37 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/model/Reservation.java
> +    @OneToOne
Ah ja een User kan meerdere Reservations hebben, klinkt logisch nu je het zegt.

2021-02-17 14:27 UTC, Daniel-Jacob approved these changes

2021-02-17 14:27 UTC, Daniel-Jacob commented on src/main/java/nl/conspect/drivedok/repositories/ReservationRepository.java
> +public interface ReservationRepository extends JpaRepository<Reservation, Long> {
Heb je wel alle methoden nodig van JpaRepository? Je kan overwegen om CrudRepository te gebruiken als het niet zo is.

2021-02-17 14:27 UTC, Daniel-Jacob commented on src/main/java/nl/conspect/drivedok/services/ReservationServiceImpl.java
> +    public ReservationServiceImpl(ReservationRepository repository) {
Impl is niet erg beschrijvend. Probeer een naam te verzinnen die dat wel is.

2021-02-17 14:27 UTC, Daniel-Jacob commented on src/test/java/nl/conspect/drivedok/services/ReservationServiceImplTest.java
> +class ReservationServiceImplTest {
Opzich zal dat niet veel uitmaken. @SpringBootTest gebruikt geen mocks maar je daadwerkelijke objecten. Dat betekent dus dat er daadwerkelijk naar de database wordt gegaan. Het enige verschil met wel of geen controller is dan je beginpunt.

2021-02-17 14:27 UTC, Daniel-Jacob commented on src/test/java/nl/conspect/drivedok/services/ReservationServiceImplTest.java
> +                .orElseThrow(() -> new RuntimeException("Reservation not persisted in test"));
is wel raar om een orElseThrow in je test te doen. Dat is logica en hoort uit je service laag te komen. Dan kan je dat vervolgens testen door een test te maken en met assertj een AssertThatThrownBy te doen en te checken dat die exceptie gegooid wordt.

2021-02-17 19:45 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/model/Reservation.java
> +    @OneToOne
Aangepast, hoop dat het zo goed staat - kunnen jullie dat bevestigen?

2021-02-17 19:46 UTC, dominicnzl commented on src/test/java/nl/conspect/drivedok/services/ReservationServiceImplTest.java
> +        assertEquals(Optional.of(reservation), service.findById(entity.getId()));
Test faalt idd als ik `testEntityManager.clear()` doe 😁

uhhh help?

2021-02-17 19:56 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/services/ReservationServiceImpl.java
> +    public ReservationServiceImpl(ReservationRepository repository) {
Ik vind namen vaak wel moeilijk maar besef me ook wel dat ze erg belangrijk zijn. Aangezien ik voorlopig 1 implementatie noem ik het voor nu: `BasicReservationService`

2021-02-17 20:02 UTC, dominicnzl commented on src/test/java/nl/conspect/drivedok/services/ReservationServiceImplTest.java
> +                .orElseThrow(() -> new RuntimeException("Reservation not persisted in test"));
is vervangen

2021-02-18 11:17 UTC, dominicnzl commented on src/test/java/nl/conspect/drivedok/services/ReservationServiceImplTest.java
> +        assertEquals(Optional.of(reservation), service.findById(entity.getId()));
tip van Daniel: voor de `.clear()` ook een `.flush()` doen, dan werkt het weer. Zal toch weer eens een jpa tutorial aanzetten

2021-02-19 10:10 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/repositories/ReservationRepository.java
> +public interface ReservationRepository extends JpaRepository<Reservation, Long> {
Moet ik even over nadenken: dezelfde vraag geldt namelijk ook voor de andere repositories. Ik houd voor nu de JpaRepo aan

2021-02-19 10:52 UTC, dominicnzl commented on src/test/java/nl/conspect/drivedok/services/ReservationServiceImplTest.java
> +class ReservationServiceImplTest {
Ik heb nu bijvoorbeeld voor de findAll() dit gedaan: `ReservationRepository` is nu een `@MockBean`

```
    @Test
    @DisplayName("Expect findall size to be 3.")
    void findAll() {
        var reservationA = new Reservation();
        var reservationB = new Reservation();
        var reservationC = new Reservation();
        var reservations = List.of(reservationA, reservationB, reservationC);
        when(service.findAll()).thenReturn(reservations);
        assertThat(service.findAll().size()).isEqualTo(3);
    }
```

Het ziet er alleen zo uit als een open deur... is dit hoe ik het ook voor de andere tests zou moeten doen?

2021-02-22 17:05 UTC, dominicnzl commented on src/test/java/nl/conspect/drivedok/services/ReservationServiceImplTest.java
> +class ReservationServiceImplTest {
integratie tests verwijderd, nu vervangen met unit test met een mock repository. Integratie tests komen pas wanneer de controller is aangemaakt, dan kan de hele keten worden gedaan.

2021-02-23 08:50 UTC, mdeinum approved these changes

2021-02-23 08:50 UTC, mdeinum commented on src/test/java/nl/conspect/drivedok/services/BasicReservationServiceTest.java
> +@ExtendWith(SpringExtension.class)
Je kunt rechstreeks mockito gebruiken en `@Mock`/`@InjectMocks` je hebt hier nog steeds de "overhead" van Spring. Gebruik dan `@ExtendWith(MockitoExtension.class)` ipv `@ExtendWith(SpringExtension.class)`

2021-02-23 09:38 UTC, dominicnzl commented on src/test/java/nl/conspect/drivedok/services/BasicReservationServiceTest.java
> +@ExtendWith(SpringExtension.class)
Thanks!

2021-02-23 09:41 UTC, Daniel-Jacob commented on src/test/java/nl/conspect/drivedok/services/BasicReservationServiceTest.java
> +@ExtendWith(SpringExtension.class)
> Kudos, SonarCloud Quality Gate passed!
> 
> [<img alt="Bug" width="16" height="16" src="https://camo.githubusercontent.com/deaad8c9d9b09977da3f9aa455689440a17356bb359560328463022a0d9d1362/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672e706e67">](https://sonarcloud.io/project/issues?id=dominicnzl_DriveDok&pullRequest=137&resolved=false&types=BUG) [<img alt="A" width="16" height="16" src="https://camo.githubusercontent.com/c51bc537468c04ce22bf2a646097b829e435b6847a82d6e663dd26de8ba24fc5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412e706e67">](https://sonarcloud.io/project/issues?id=dominicnzl_DriveDok&pullRequest=137&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=dominicnzl_DriveDok&pullRequest=137&resolved=false&types=BUG)
> [<img alt="Vulnerability" width="16" height="16" src="https://camo.githubusercontent.com/60273222b26453a76e9c369287fa0106b151cbaae4fa4ce00e149b269a0fac67/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792e706e67">](https://sonarcloud.io/project/issues?id=dominicnzl_DriveDok&pullRequest=137&resolved=false&types=VULNERABILITY) [<img alt="A" width="16" height="16" src="https://camo.githubusercontent.com/c51bc537468c04ce22bf2a646097b829e435b6847a82d6e663dd26de8ba24fc5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412e706e67">](https://sonarcloud.io/project/issues?id=dominicnzl_DriveDok&pullRequest=137&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=dominicnzl_DriveDok&pullRequest=137&resolved=false&types=VULNERABILITY)
> [<img alt="Security Hotspot" width="16" height="16" src="https://camo.githubusercontent.com/a0723b4c04ec36cc8d010cca748afdc6300592f020130edca7403ea5b17ffe35/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742e706e67">](https://sonarcloud.io/project/security_hotspots?id=dominicnzl_DriveDok&pullRequest=137&resolved=false&types=SECURITY_HOTSPOT) [<img alt="A" width="16" height="16" src="https://camo.githubusercontent.com/c51bc537468c04ce22bf2a646097b829e435b6847a82d6e663dd26de8ba24fc5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412e706e67">](https://sonarcloud.io/project/security_hotspots?id=dominicnzl_DriveDok&pullRequest=137&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=dominicnzl_DriveDok&pullRequest=137&resolved=false&types=SECURITY_HOTSPOT)
> [<img alt="Code Smell" width="16" height="16" src="https://camo.githubusercontent.com/1b640677486022b878fa0367aa2b5cffad9b009d2ff2fc3440cbd7f8da85fe55/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2e706e67">](https://sonarcloud.io/project/issues?id=dominicnzl_DriveDok&pullRequest=137&resolved=false&types=CODE_SMELL) [<img alt="A" width="16" height="16" src="https://camo.githubusercontent.com/c51bc537468c04ce22bf2a646097b829e435b6847a82d6e663dd26de8ba24fc5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412e706e67">](https://sonarcloud.io/project/issues?id=dominicnzl_DriveDok&pullRequest=137&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=dominicnzl_DriveDok&pullRequest=137&resolved=false&types=CODE_SMELL)
> 
> [<img alt="100.0%" width="16" height="16" src="https://camo.githubusercontent.com/09ce026c321b1f22435cfe26c44012ab2cd647042a3300a035d6df6589b3cac8/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f3130302e706e67">](https://sonarcloud.io/component_measures?id=dominicnzl_DriveDok&pullRequest=137&metric=new_coverage&view=list) [100.0% Coverage](https://sonarcloud.io/component_measures?id=dominicnzl_DriveDok&pullRequest=137&metric=new_coverage&view=list)
> [<img alt="0.0%" width="16" height="16" src="https://camo.githubusercontent.com/17c8580971832aaa80226d5b1c5c61cc2f9ef6a863fc6f6bae0ab2c7d45165ed/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332e706e67">](https://sonarcloud.io/component_measures?id=dominicnzl_DriveDok&pullRequest=137&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=dominicnzl_DriveDok&pullRequest=137&metric=new_duplicated_lines_density&view=list)

Hoe dan? :D

2021-02-23 09:55 UTC, mdeinum approved these changes

2021-02-23 10:30 UTC, GeenEva approved these changes

2021-02-23 10:30 UTC, merged