116 reservations controllers - mapstruct - refactoring vehicle and user controllers
dominicnzl/DriveDok pull request #139
Opened 2021-02-25 10:54 UTC by dominicnzl

Hier wilde ik de ReservationRestController gebruik laten maken van DTO's ipv de entity. Het probleem is eerder door @GeenEva aangekaart in #127 . Ik heb hiervoor daarom op aanraden van @mdeinum en @Daniel-Jacob gebruik gemaakt van MapStruct om de mapping te faciliteren. 

Een reservering is in mijn ogen een object die een tijd(span) combineert met User, Vehicle en ParkingSpot (zou wellicht ook ParkingZone kunnen zijn - hier wordt nog over nagedacht). Hierom heb ik de RestControllers voor User en Vehicle meteen refactored.

2021-03-01 11:40 UTC, Daniel-Jacob approved these changes

2021-03-01 11:40 UTC, Daniel-Jacob commented on src/main/java/nl/conspect/drivedok/controllers/ReservationRestController.java
> +                .map(service::save);
Dit is geen map :). Wat je hier doet is geen transformation maar een actie. Ik zou een andere methode zoeken zoals een foreach of iets dergelijks die een save doet.

2021-03-01 12:03 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/controllers/ReservationRestController.java
> +        return of(service.findById(id).map(mapper::reservationToDto));
Bedoel je hier dat ik in mijn return waarde de `ResponseEntity<ReservationDto>` kan vervangen met `ResponseEntity<Reservation>`?

2021-03-01 12:14 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/controllers/ReservationRestController.java
> +        return ok(mapper.reservationsToDtos(service.findAll()));
Ik begrijp even niet wat je bedoelt. Kan me wel herinneren dat je een tijdje geleden iets zei over dat ik een `EntityList` zou moeten returnen ipv een `List<Entity>`, bedoel je hier dat ik een `DtoList` zou moeten returnen?

2021-03-02 14:37 UTC, Daniel-Jacob commented on src/main/java/nl/conspect/drivedok/controllers/ReservationRestController.java
> +        return ok(mapper.reservationsToDtos(service.findAll()));
Die comment heeft meer te maken met dat je doorsijpeling hebt van een andere laag naar je domein laag. Hier heb ik het slechts over de naamgeving. Dus het expliciet benoemen van iets als dto. Ik vind ReservationResponse dan netter dan ReservationDto.

2021-03-02 17:28 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/controllers/ReservationRestController.java
> +                .map(service::save);
samen besproken: service.save returnt een Reservation en is hier dus ok

2021-03-02 17:30 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/controllers/ReservationRestController.java
> +        return of(service.findById(id).map(mapper::reservationToDto));
Samen besproken: kan beter een ResponseEntity<Reservation> returnen. Daardoor is de return waarde ook encapsulated. Wanneer ik dat doe is voorgaande comment op regel 38-41 ook opgelost :)

2021-03-03 08:25 UTC, mdeinum requested changes

2021-03-03 08:25 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/controllers/ReservationRestController.java
> +        return status(CREATED).body(service.save(mapper.dtoToReservation(dto)));
Status `CREATED` met een body is over het algemeen raar. Je geeft over het algemeen de URL terug waar je het object kunt vinden. Vandaar ook de `ResponseEntity.created(URI)` methode.

2021-03-03 08:25 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/controllers/ReservationRestController.java
> +        if (service.findById(id).isEmpty()) {
Je gebruikt `Optional` nu als glorified if statement, don't. Gebruik de map en `orElse` om een functionele flow te maken.

2021-03-03 08:25 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/controllers/VehicleRestController.java
> +    private final VehicleService service;
Ik zou `vehicleService` als naam gebruiken, met meerdere services wordt dit onduidelijk.

2021-03-03 08:25 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/model/ReservationDto.java
> +public class ReservationDto {
Met lombok kun je deze code wat versimpelen of gebruik een `record` (al weet ik niet of MapStruct die al ondersteunt).

2021-03-03 08:25 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/utilities/BasicLocalDateTimeMapper.java
> +public class BasicLocalDateTimeMapper {
Snap niet zo goed waar deze mapper voor dient? Aan de voorkant gebruik je de browser en zou je data moeten versturen in ISO formaat dan wordt conversie automatisch gedaan.

2021-03-03 08:25 UTC, mdeinum commented on src/test/java/nl/conspect/drivedok/controllers/ReservationRestControllerTest.java
> +    ReservationMapperImpl mapper;
Waarom een mock van de imll en niet van de interface? Als MapStruct een andere naming strategy bedenkt compileert het niet meer.

2021-03-03 08:25 UTC, mdeinum commented on src/test/java/nl/conspect/drivedok/controllers/ReservationRestControllerTest.java
> +    BasicReservationService service;
Gebruik de interface als mock niet de concrete implementatie. Je hebt die interface niet voor niks.

2021-03-03 08:50 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/controllers/ReservationRestController.java
> +        return status(CREATED).body(service.save(mapper.dtoToReservation(dto)));
ok, aangepast ✔

2021-03-03 09:45 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/controllers/ReservationRestController.java
> +        if (service.findById(id).isEmpty()) {
```
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        return service.findById(id)
                .map(entity -> {
                    service.delete(entity);
                    return noContent().<Void>build();
                })
                .orElseGet(() -> notFound().build());
    }
```
Ik heb er dit van gebakken, kreeg het niet voor elkaar om een code block in de map te vermijden. Die `service.delete(entity)` geeft void terug waardoor mijn stream niet verder gaat - of maakt dat niet uit... Of misschien dat ik daar een methode voor moet extracten?

2021-03-03 09:46 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/controllers/VehicleRestController.java
> +    private final VehicleService service;
ok ✔

2021-03-03 09:48 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/model/ReservationDto.java
> +public class ReservationDto {
Ik denk dat dit een aanpassing is die z'n eigen issue verdient. Zal het met @GeenEva bespreken of we Lombok gaan gebruiken.

2021-03-03 09:54 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/utilities/BasicLocalDateTimeMapper.java
> +public class BasicLocalDateTimeMapper {
Ik dacht dat ik dit nodig had voor mijn ReservationMapper waar ik deze BasicLocalDateTimeMapper gebruik. Nu zie ik ook dat het zonder werkt. Hmm weet dus niet meer waarom ik het nodig dacht te hebben. Zal het verwijderen.

2021-03-03 09:58 UTC, dominicnzl commented on src/test/java/nl/conspect/drivedok/controllers/ReservationRestControllerTest.java
> +    ReservationMapperImpl mapper;
oh ja... ✔

2021-03-03 09:58 UTC, dominicnzl commented on src/test/java/nl/conspect/drivedok/controllers/ReservationRestControllerTest.java
> +    BasicReservationService service;
ok ✔

2021-03-03 13:13 UTC, GeenEva approved these changes

2021-03-03 14:12 UTC, merged