Reservations -> thymeleaf controllers
dominicnzl/DriveDok pull request #142
Opened 2021-03-04 14:12 UTC by dominicnzl

not ready for review...

2021-03-08 10:28 UTC, Daniel-Jacob approved these changes

2021-03-08 10:28 UTC, Daniel-Jacob commented on src/main/java/nl/conspect/drivedok/controllers/ReservationController.java
> +    public static final String EDITPAGE = "reservation-editpage";
deze static final variabelen zijn een mooie candidaat om in je application.properties te stoppen en te injecteren met @Value annotatie.

2021-03-08 10:28 UTC, Daniel-Jacob commented on src/main/java/nl/conspect/drivedok/controllers/UserController.java
> +    public static final String USER_LISTPAGE = "user-listpage";
al dit kan je in een application.properties stoppen en injecteren

2021-03-08 18:00 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/controllers/ReservationController.java
> +    public static final String EDITPAGE = "reservation-editpage";
cool, niet aan gedacht

2021-03-10 10:39 UTC, dominicnzl commented
- Thymeleaf listpage en editpage aangemaakt voor Reservation. Hierbij is het een en ander meegenomen vwb User en Vehicle maar niet alles. Zo moet bijvoorbeeld voor de UserController nog worden ingeregeld dat de parameter wordt omgezet in de dto's ipv de entiteiten. Dat doe ik graag met een aparte issue.
- ObjectMapper weggegooid, DateTimeFormatter annotaties toegevoegd aan ReservationDto

2021-03-10 12:51 UTC, mdeinum requested changes

2021-03-10 12:51 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/controllers/ReservationController.java
> +        final var mav = new ModelAndView(listpage);
`final` als onderdeel van een declaratie binnen een method vind ik zelf nooit zo nodig (behalve als de compiler het vindt :) ). Verhoogt de cognitieve load bij het lezen zonder dat het een echte meerwaarde biedt. 

Maar dat is IMHO natuurlijk.

2021-03-10 12:51 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/controllers/ReservationController.java
> +    public ModelAndView handleGetId(@PathVariable Long id) {
ipv. een `null` check kun je ook een `Optional<Long>` meegeven en deze via `map` or `orElse` mappen ipv. een shorthand if notatie.

2021-03-10 12:51 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/controllers/ReservationController.java
> +            return handleGetId(dto.getId());
Kans met deze oplossing is dat je de ingevoerde waardes en foutmeldingen kwijtraakt aan de voorkant.

2021-03-10 12:51 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/controllers/UserController.java
> +    @Value("${user.list.page}")
Wat is de meerwaarde van het externaliseren van de naam van de pagina? Je kunt hem niet zomaar aanpassen er zal altijd een bijbehorend template moeten zijn. Voegt imho niks toe behalve complexiteit.

2021-03-10 14:35 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/controllers/ReservationController.java
> +        final var mav = new ModelAndView(listpage);
oh omdat de scope dan sowieso beperkt blijft tot die methode? Zal het onthouden 👍

2021-03-10 14:52 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/controllers/UserController.java
> +    @Value("${user.list.page}")
Wat ik eerst had was `public static final` fields (zodat die ook in de test assertions konden). Het leek me wel mooi om herhaling te voorkomen en om alle template namen bij elkaar te hebben als een soort index. Alleen merkte ik vanmorgen ook dat een schrijffout snel gemaakt is, bijv `@Value("${user.list.page")`. Het is inderdaad meer complex/foutgevoelig. Ik denk dat ik het terug zet.

https://github.com/dominicnzl/DriveDok/pull/142/files/cb6d63e144893047b052e58c221cb46f0b470e95#r589316187

2021-03-10 14:59 UTC, mdeinum approved these changes

2021-03-10 15:44 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/controllers/ReservationController.java
> +    public ModelAndView handleGetId(@PathVariable Long id) {
die `Optional<Long>` in de parameter kan denk ik ook null zijn, dan heb ik alsnog een null check nodig? Of bedoel je iets anders?

2021-03-10 18:25 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/controllers/ReservationController.java
> +    public ModelAndView handleGetId(@PathVariable Long id) {
Een optional is niet `null` dan heb je een lege `Optional` dat is nou juist het mooie van een `Optional`.

2021-03-10 19:13 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/controllers/ReservationController.java
> +            return handleGetId(dto.getId());
Ik heb dit er van gebakken: 
```
    @PostMapping
    public ModelAndView handlePost(@ModelAttribute ReservationDto dto, BindingResult bindingResult) {
        if (bindingResult.hasErrors()) {
            var mav = handleCreate();
            mav.addObject(bindingResult);
            return mav;
        }
        var entity = mapper.dtoToReservation(dto);
        reservationService.save(entity);
        return handleGet();
    }
```
In de test kan ik expres een binding error triggeren door een waarde voor startDate in te geven dat niet voldoet aan de `@DateTimeFormatter("yyyy-MM-dd")`. Vanuit mijn browser lukt dat niet echt dus weet nou niet zeker of dit de juiste oplossing is... graag je input :)

2021-03-10 19:16 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/controllers/UserController.java
> +    @Value("${user.list.page}")
heb het weer teruggezet

2021-03-11 06:45 UTC, mdeinum requested changes

2021-03-11 06:45 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/controllers/ReservationController.java
> +            mav.addObject(bindingResult);
Dit is niet de juiste manier om het `BindingResult` toe te voegen aan een `ModelAndView`. Idealiter wat je zou doen is 

```java
var mav = new ModelAndView("view", bindingResult.getModel());
```

Dit zorgt ervoor dat de foutmeldingen, de origineel ingevoerde waardes etc. allemaal bewaard blijven. Oftewel je zou dus eigenlijk niet `handleGetId` moeten aanroepen omdat dat toch echt een andere use-case is.

2021-03-11 11:55 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/controllers/ReservationController.java
> +            mav.addObject(bindingResult);
ah, dat is ook zo: was me niet duidelijk hoe ik de originele data van de een naar het ander kreeg. Ben er wat verder in gaan klikken en zie ook dat er als derde parameter een HttpStatus kan worden meegegeven.

2021-03-11 13:48 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/controllers/ReservationController.java
> +            mav.addObject(bindingResult);
Ik kom in de problemen omdat ik bij de view aangeef dat mijn object een Reservation is ipv een ReservationDto. Zal dus het een en ander moeten ombouwen.

2021-03-11 14:21 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/controllers/ReservationController.java
> +            mav.addObject(bindingResult);
Ok, ik denk dat ik het heb gefixt: de template gebruikt nu de dto om alle velden te voeren. Daarmee lukt de fieldbinding voor de startTime&Date en endTime&Date ook weer

2021-03-12 14:19 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/controllers/ReservationController.java
> +        return handleGet();
Om problemen in de browser te voorkomen is het beter om een redirect the doen na een post. Ook wel bekend als het [post-redirect-get](https://en.wikipedia.org/wiki/Post/Redirect/Get) pattern. Hiermee voorkom je dat bij een browser refresh de post opnieuw wordt gestuurd.

2021-03-12 17:25 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/controllers/ReservationController.java
> +        return handleGet();
tof, ik kende dit principe helemaal niet. Ik zie dat er een HttpStatus 303 wordt verwacht. In de huidige opzet doe ik aan het einde van `handlePost` een `GET` op /reservations en toon daarmee de hele lijst van reserveringen. Het is me even niet duidelijk of dat juist is, of dat ik beter een redirect kan doen naar `GET` op /reservations/{id}

2021-03-15 08:16 UTC, mdeinum approved these changes

2021-03-15 12:41 UTC, GeenEva approved these changes

2021-03-15 12:41 UTC, merged