146 intro locale
dominicnzl/DriveDok pull request #151
Opened 2021-03-19 12:30 UTC by dominicnzl

In deze PR heb ik de localisatie geimplementeerd en de front-end als bijkomend klusje meegenomen. Ik heb hiervoor in de `DriveDokApplication` deze beans aangemaakt: `localeChangeInterceptor`, `localeResolver`, `messageSource`, `getValidator`.

De resource bundle zit in `resources/i18n` en is ingedeeld qua entiteit. Hiervan heb ik het naar eigen inzicht ingedeeld, wellicht dat jullie hier een betere idee over hebben en kunnen delen.

Qua frontend heb ik een `layout.html` aangemaakt met fragments die ik via `th:replace` in de templates zet. Daar zit ook een javascript dingetje tussen om wanneer je op de rij klikt een redirect te doen naar `/{entiteit}/{id}`.

Als laatste: is me niet helemaal duidelijk hoe en of ik die localisatie moet testen. Tips?

2021-03-20 19:20 UTC, dominicnzl commented
closes #146 #106

2021-03-22 08:28 UTC, mdeinum requested changes
TIP: Kijk nog eens naar het Layout Dialect van Thymeleaf (of maak daar een story van).

2021-03-22 08:28 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/DrivedokApplication.java
> +    public MessageSource messageSource() {
Deze hoef je dus niet te configureren maar met een `spring.messages.basename=i18n/messages` in de `application.properties` ben je er al. De encoding is default al UTF-8 dan en hoef je ook niet op te nemen, kan wel door `spring.messages.encoding=UTF-8` op te nemen als properties.

2021-03-22 08:28 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/DrivedokApplication.java
> +public class DrivedokApplication implements WebMvcConfigurer {
Het is beter om deze additionele configuratie in een losse `@Configuration` class te zetten. Voor je (integratie) testen is het dan te scheiden wat wel en niet gestart moet worden.

2021-03-22 08:28 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/model/User.java
> +    @Size(max = 64, min = 1, message = "{valid.string.range}")
Estetisch gezien zou ik `min` vooraan zetten.

2021-03-22 08:28 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/utilities/ZoneMapper.java
> +        unmappedTargetPolicy = ReportingPolicy.IGNORE)
Zelf zou ik minimaal WARNING als policy gebruiken. Mocht je dan zaken wijzigen krijg je lig een melding in je logging. Zelf gebruik ik meestal ERROR zodat je compilatie/test errors krijgt en je altijd met nieuwe properties goed moet blijven checken of je mappers blijven werken.

2021-03-22 08:28 UTC, mdeinum commented on src/main/resources/application.properties
> +spring.messages.use-code-as-default-message=true
Deze setting is min of meer ongebruikt aangezien je zelf een `MessageSource` configureert en niet de configuratie aan Spring Boot over laat.

2021-03-22 09:00 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/DrivedokApplication.java
> +public class DrivedokApplication implements WebMvcConfigurer {
ga ik doen  👍

2021-03-22 09:01 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/utilities/ZoneMapper.java
> +        unmappedTargetPolicy = ReportingPolicy.IGNORE)
done

2021-03-22 09:04 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/model/User.java
> +    @Size(max = 64, min = 1, message = "{valid.string.range}")
Ja dat ben ik met je eens, ik zag ook bij het invullen van de message parameters dat in de volgorde {field} {max} {min} gaat. Waar wordt dat eigenlijk bepaald en zitten er ook andere argumenten tussen?

`valid.string.range={0} should be between {2} and {1} characters`

2021-03-22 09:16 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/DrivedokApplication.java
> +    public MessageSource messageSource() {
Ik dacht dat ik het expliciet moest maken omdat ik het bij de `LocalValidatorFactoryBean` als `ValidationMessageSource` zet. Nu zie ik dat het met de `messageSource` als argument ook werkt:

```
    @Bean
    public LocalValidatorFactoryBean getValidator(MessageSource messageSource) {
        var bean = new LocalValidatorFactoryBean();
        bean.setValidationMessageSource(messageSource);
        return bean;
    }
```

thanks!

2021-03-22 09:18 UTC, dominicnzl commented on src/main/resources/application.properties
> +spring.messages.use-code-as-default-message=true
Ik heb nu de MessageSource configuratie er weer uit gehaald en gebruik gemaakt van de application.properties settings

2021-03-22 09:27 UTC, dominicnzl commented
> TIP: Kijk nog eens naar het Layout Dialect van Thymeleaf (of maak daar een story van).

Ik heb hier een issue voor aangemaakt en ga er vandaag nog aan. In deze PR wil ik het vooral bij i18n houden (frontend aanpassingen waren meer als gevolg van boy scout rule)

2021-03-22 10:38 UTC, mdeinum approved these changes

2021-03-22 15:12 UTC, GeenEva approved these changes

2021-03-22 15:12 UTC, GeenEva commented on src/main/java/nl/conspect/drivedok/model/ZoneDto.java
> +    public void setParkingSpots(Set<ParkingSpot> parkingSpots) {
ik meen me te herinneren dat collection fields setten anders moest, iets met "the data can be modified outside the scope of the setter method, which breaks the encapsulation purpose of the setter" volgens hier https://dzone.com/articles/java-getter-and-setter-basics-common-mistakes-and , en hij doet iets met clone(), maar omdat wij dat eerder ook niet hebben gedaan vroeg ik me af is dat dan hoe het moet? @mdeinum  kunnen we dit gewoon zo laten of moeten we dit anders doen? We zijn het een keer eerder tegen gekomen in DriveDok, maar weet niet meer waar

2021-03-23 06:55 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/model/ZoneDto.java
> +    public void setParkingSpots(Set<ParkingSpot> parkingSpots) {
Waarom heeft een Dto een relatie met een entity? Dat zou ook een dto m moeten zijn. Voor een entity moet je altijd zorgen voor een add/remove ipv. een set op een collectie omdat je anders dingen stuk maakt :). Maar hier zou je een DTO moeten linken met een DTO en niet met een entity.

2021-03-24 14:24 UTC, mdeinum commented on src/main/java/nl/conspect/drivedok/model/Vehicle.java
>      private String licencePlate;
Waarom? Wil je alleen NL kentekens toestaan? (Ik vind dat discriminatie ;) ). Maar limiteren op alleen A-Z en 0-9 is misschien wel een idee (al heb je dan mogelijk een issue met Arabische en Oosterse kentekens...

2021-03-24 21:29 UTC, dominicnzl commented on src/main/java/nl/conspect/drivedok/model/Vehicle.java
>      private String licencePlate;
In een eerder stadium heb ik hiervoor #93 al in het leven geroepen. Op de rdw site staan ook de validatie regels voor NL kentekenplaten, had zelf eigenlijk ook niet aan buitenlandse gedacht. Oeps.

2021-03-29 07:46 UTC, GeenEva approved these changes

2021-03-29 07:47 UTC, merged