Logic for updating parkingzone
dominicnzl/DriveDok pull request #57
Opened 2020-12-31 12:16 UTC by GeenEva

because de logic for working with a @version of type DateTime is giving a lot of complications when passing it from thymeleaf to spring, we decided to take this field out of the parkingzone for now and perhaps put it back in a later stadium

2020-12-31 12:51 UTC, dominicnzl requested changes
Je zult iets zinnigs met de ParkingSpots in ParkingZoneServiceTest moeten doen of anders niet in de Test zetten.

2020-12-31 12:51 UTC, dominicnzl commented on src/test/java/nl/conspect/drivedok/services/ParkingZoneServiceTest.java
>          ParkingSpotService parkingSpotService;
Waarom worden hier in de test class ParkingSpots gedeclareerd en ParkingSpotService geinjecteerd? Ik zie hier geen Assertions op ParkingSpots of mis ik iets?

2020-12-31 12:54 UTC, GeenEva commented on src/test/java/nl/conspect/drivedok/services/ParkingZoneServiceTest.java
>          ParkingSpotService parkingSpotService;
ja omdat de parkingspot een veld is van de zone, moet deze ook gepersist worden

2021-01-03 09:05 UTC, dominicnzl approved these changes

2021-01-03 09:05 UTC, merged